name: ddomlabbackend  # Environment name

dependencies:  # Packages should be installed through conda if possible
  - python=3.11  # Python version
  - pre-commit
  - ruff
  - pyyaml
  - urllib3
  - requests
  - pypdf
  - tabulate
  - pandas
  - flask
  - flask-cors
  - gunicorn
  - pip
  - pip:  # Install additional packages through pip if they're not available in the default conda channel
    - pubchempy
    - elabapi_python==5.6.0
    - blabel
    - rdkit
